### ISSUE TITLE
There is something wrong with the slowModEnd method?

### ISSUE THREAD

**Issue by elvinege-zz** [pcevikogullari/OzU-CS320#8]
When slow mod is activated, it wont stop

**Comment by oguzgelal** [comment]
This could be about variables, I will check shortly

**Comment by oguzgelal** [comment]
Nope, its not the variables it is slowModEnd method @turushanaktay ??

**Comment by turushan** [comment]
problem fixed

**Comment by elvinege-zz** [comment]
Problem wasn't fixed check it again @oguzgelal @turushanaktay @begumtokuyucu @pcevikogullari

**Comment by turushan** [comment]
my bad @elvinege , fixed now, have a nice day bebişler.

**Comment by oguzgelal** [comment]
It took 3 years to fix this?? 😒 @turushanaktay

**Comment by pcevikogullari** [comment]
still doesn't work on my computer... @turushanaktay

**Comment by turushan** [comment]
it runs even on this computer @pcevikogullari , not my problem.

![screen shot 2017-04-12 at 17 52 59](https://cloud.githubusercontent.com/assets/4019257/24964072/eccab00a-1fa8-11e7-9df4-5a310a0c4487.png)

**Comment by turushan** [comment]
@oguzgelal it took 3 years for our QA girl @elvinege  to detect it 🤦‍♂️ fix in 10 seconds 😏
